In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
data=pd.read_csv('spam.csv')

In [3]:
data

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
Category = {'spam': 1,'ham': 0}
data.Category = [Category[item] for item in data.Category] 
data

Category                                            Message
0            0  Go until jurong point, crazy.. Available only ...
1            0                      Ok lar... Joking wif u oni...
2            1  Free entry in 2 a wkly comp to win FA Cup fina...
3            0  U dun say so early hor... U c already then say...
4            0  Nah I don't think he goes to usf, he lives aro...
...        ...                                                ...
5567         1  This is the 2nd time we have tried 2 contact u...
5568         0               Will ü b going to esplanade fr home?
5569         0  Pity, * was in mood for that. So...any other s...
5570         0  The guy did some bitching but I acted like i'd...
5571         0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
df_x=data["Message"]
df_y=data["Category"]

In [6]:
df_x

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [7]:
cv=TfidfVectorizer(min_df=1,stop_words='english')

In [8]:
x_train,x_test,y_train,y_test=train_test_split(df_x,df_y,test_size=.2)
x_train

1575    My sis is catching e show in e afternoon so i'...
2050             How much is blackberry bold2 in nigeria.
3017    &lt;#&gt;  is fast approaching. So, Wish u a v...
589                           Ya srsly better than yi tho
4830    How long before you get reply, just defer admi...
                              ...                        
5318    Good morning, my Love ... I go to sleep now an...
5003           You still around? Looking to pick up later
1423    Congratulations ur awarded either £500 of CD g...
1860            What's up. Do you want me to come online?
4130                 Me i'm not workin. Once i get job...
Name: Message, Length: 4457, dtype: object

In [9]:
x_traincv1 = cv.fit_transform(["Hello mr, how are you?, how is it doing", "Whats up dude?"])

In [10]:
x_traincv1.toarray()

array([[0.57735027, 0.        , 0.57735027, 0.57735027, 0.        ],
       [0.        , 0.70710678, 0.        , 0.        , 0.70710678]])

In [11]:
cv.get_feature_names()

['doing', 'dude', 'hello', 'mr', 'whats']

In [12]:
cv1=TfidfVectorizer()

In [13]:
x_traincv=cv1.fit_transform(x_train)

In [14]:
a=x_traincv.toarray()
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [15]:
a[45]

array([0., 0., 0., ..., 0., 0., 0.])

In [16]:
cv1.inverse_transform(a[0])

[array(['afternoon', 'catching', 'her', 'in', 'is', 'lor', 'my', 'not',
        'or', 'show', 'sis', 'so', 'tmr', 'today', 'wan', 'watch',
        'watching'], dtype='<U34')]

In [41]:
x_train.iloc[87]

'I am waiting machan. Call me once you free.'

In [18]:
mnb= MultinomialNB()

In [19]:
y_train=y_train.astype('int')

In [20]:
mnb.fit(x_traincv,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [21]:
x_testcv=cv1.transform(x_test)


In [22]:
pred=mnb.predict(x_testcv)

In [23]:
pred

array([0, 1, 0, ..., 0, 0, 0])

In [24]:
actual=np.array(y_test)

In [25]:
actual

array([0, 1, 0, ..., 0, 0, 0])

In [26]:
count=0
for i in range (len(pred)):
    if pred[i]==actual[i]:
        count=count+1

In [27]:
count

1066

In [28]:
len(pred)

1115

In [29]:
count/len(pred)

0.9560538116591928

In [30]:

mnb.predict(x_testcv[43])
x_testcv[43]

<1x7787 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [31]:
x_test.iloc[43]

'Ffffffffff. Alright no way I can meet up with you sooner?'

In [32]:
x_train[9]

'Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030'

In [33]:
def pred(msg):
    msg = cv1.transform([msg])
    prediction = mnb.predict(msg)
    return prediction[0]


In [35]:
pred("['hello,','How','are', 'you', 'are']")

0

In [42]:
pred("['Get','camera', 'for', 'Free!', 'Call','The', 'Mobile', 'Update', 'Co', 'FREE', 'on', '08002986030']']")

1