In [1]:
#numpy- adds multidimention support to visual data
#matplotlib- represnation
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier, AdaBoostClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [2]:
data = pd.read_csv('data.csv')
gender = {'M': 0,'F': 1}
data.Gender = [gender[item] for item in data.Gender] 
data

Gender  Heart rate   Temp   RR  SPO2  Condition
0        0          193   36.7  22    98          0
1        0           99   37.2  12    97          0
2        0           80   36.0  29    97          1
3        0           73   36.8  22    98          1
4        0           72   36.0  20    96          0
5        0          116   36.8  22    98          0
6        0           81   37.1  14    96          1
7        0           90   37.0  24    96          0
8        0           97   36.8  16    97          1
9        0          100   37.3  22    99          1
10       1           98   37.0  15    77          1
11       1           91   36.5  18    99          1
12       1           98   36.3  18    89          1
13       1          103   37.2  20    99          0
14       1           92   36.4  18    99          0
15       1           80   36.5  20    98          1
16       1          103   36.4  20    98          1
17       1           81   36.9  16    99          0
18       0          129   37.0  22    96          0
19       0          121   37.6  11    97          1
20       0           80   36.7  29    98          0
21       0           73   37.1  18    96          0
22       0           74   36.7  28    94          1
23       0           96   36.9  26    97          1
24       0           73   37.5  22    97          1
25       0           89   38.0  28    97          1
26       0           70   37.3  24    98          1
27       0          130   39.3  18    98          0
28       1           95   36.9  18    80          0
29       1          114   37.7  14    98          1
30       1           79   37.3  22    97          1
31       1          115   37.6  10    91          0
32       1          100   36.9  21    88          1
33       1          101   37.2  18    98          1
34       1          119   36.7  22    98          0
35       1          105   37.6  16    99          1
36       0          103   36.8  18    96          1
37       0           82   36.5  14    96          0
38       0           93   37.1  20    99          1
39       0           84   36.4  18    98          0
40       0           62   36.3  22    99          1
41       0           83   36.5  18    98          0
42       0           72   37.1  16    97          1
43       0           84   37.3  25    98          0
44       0           79   37.1  14    98          1
45       0           73   36.8  26    98          1
46       1           99   36.8  18    69          0
47       1           96   36.7  24    91          1
48       1           83   36.7  22    98          1
49       1          102   36.5  22    97          1
50       1           94   36.5  24    96          1
51       1          108   36.8  20    98          0
52       1          107   36.4  16    97          0
53       1           76   36.7  16   100          1

In [3]:
dfx=data.iloc[:,0:5]
dfx

Gender  Heart rate   Temp   RR  SPO2
0        0          193   36.7  22    98
1        0           99   37.2  12    97
2        0           80   36.0  29    97
3        0           73   36.8  22    98
4        0           72   36.0  20    96
5        0          116   36.8  22    98
6        0           81   37.1  14    96
7        0           90   37.0  24    96
8        0           97   36.8  16    97
9        0          100   37.3  22    99
10       1           98   37.0  15    77
11       1           91   36.5  18    99
12       1           98   36.3  18    89
13       1          103   37.2  20    99
14       1           92   36.4  18    99
15       1           80   36.5  20    98
16       1          103   36.4  20    98
17       1           81   36.9  16    99
18       0          129   37.0  22    96
19       0          121   37.6  11    97
20       0           80   36.7  29    98
21       0           73   37.1  18    96
22       0           74   36.7  28    94
23       0           96   36.9  26    97
24       0           73   37.5  22    97
25       0           89   38.0  28    97
26       0           70   37.3  24    98
27       0          130   39.3  18    98
28       1           95   36.9  18    80
29       1          114   37.7  14    98
30       1           79   37.3  22    97
31       1          115   37.6  10    91
32       1          100   36.9  21    88
33       1          101   37.2  18    98
34       1          119   36.7  22    98
35       1          105   37.6  16    99
36       0          103   36.8  18    96
37       0           82   36.5  14    96
38       0           93   37.1  20    99
39       0           84   36.4  18    98
40       0           62   36.3  22    99
41       0           83   36.5  18    98
42       0           72   37.1  16    97
43       0           84   37.3  25    98
44       0           79   37.1  14    98
45       0           73   36.8  26    98
46       1           99   36.8  18    69
47       1           96   36.7  24    91
48       1           83   36.7  22    98
49       1          102   36.5  22    97
50       1           94   36.5  24    96
51       1          108   36.8  20    98
52       1          107   36.4  16    97
53       1           76   36.7  16   100

In [4]:
dfy=data.iloc[:,5]
dfy

0     0
1     0
2     1
3     1
4     0
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    1
13    0
14    0
15    1
16    1
17    0
18    0
19    1
20    0
21    0
22    1
23    1
24    1
25    1
26    1
27    0
28    0
29    1
30    1
31    0
32    1
33    1
34    0
35    1
36    1
37    0
38    1
39    0
40    1
41    0
42    1
43    0
44    1
45    1
46    0
47    1
48    1
49    1
50    1
51    0
52    0
53    1
Name: Condition, dtype: int64

In [5]:
x_train,x_test,y_train,y_test=train_test_split(dfx,dfy,test_size=0.25)

In [6]:
#decision tree
dt = DecisionTreeClassifier()
#fitting th data
dt.fit(x_train,y_train)


dt.score(x_test,y_test)

0.6428571428571429

In [7]:
dt.score(x_train,y_train) #this is overfitting.. therefore predcition is not very good

1.0

In [8]:
#HOW THE SCORE WAS ACTUALLY CALCULATED
pred = dt.predict(x_test)
pred

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0])

In [9]:
actual=np.array(y_test)
actual

array([0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1])

In [12]:
count=0
for i in range (len(pred)):
    if pred[i]==actual[i]:
        count=count+1
        
count

9

In [13]:
len(pred)

14

In [15]:
acuracy= count/len(pred)
acuracy

0.6428571428571429

In [17]:
#implementing Random Forest
rf=RandomForestClassifier(n_estimators=10)
rf.fit(x_train,y_train.values.ravel())
#.values will give the values in an array. (shape: (n,1)
#.ravel will convert that array shape to (n, )
#The problem was that the labels were in a column format while it expected it in a row. use np.ravel()

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [18]:
rf.score(x_test,y_test)

0.5

In [19]:
rf.score(x_train,y_train) # not completely overfitting

0.95

In [20]:
#HOW SCORE WAS ACTUALLY CALCULATED
pred = rf.predict(x_test)
pred

array([0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1])

In [22]:
actual=np.array(y_test)
actual

array([0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1])

In [23]:
count=0
for i in range (len(pred)):
    if pred[i]==actual[i]:
        count=count+1
        
count

7

In [25]:
accuracy= count/ len(pred) 
accuracy

0.5

In [26]:
#BAGGING CLASSIFIER
bg=BaggingClassifier(DecisionTreeClassifier(), max_samples=0.5, max_features=1.0)
bg.fit(x_train,y_train.values.ravel())


BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None,
                                                        criterion='gini',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort=False,
                                                        random_state=None,
                                                        splitter='best'),
    

In [27]:
bg.score(x_test,y_test)

0.5

In [28]:
bg.score(x_train,y_train)

0.775

In [29]:
#boosting reduces overfitting and variance
adb = AdaBoostClassifier(DecisionTreeClassifier(),learning_rate=1)

In [30]:
adb.fit(x_train,y_train.values.ravel())
adb.score(x_test,y_test)

0.5714285714285714

In [31]:
#USING 3 CLASSIFIERS TOGETHER
lr = LogisticRegression()
dt=DecisionTreeClassifier()
svm=SVC(kernel='poly',degree=2, gamma='auto')

In [33]:
evc = VotingClassifier( estimators=[('lr',lr),('dt',dt),('svm',svm)],voting='hard')
evc.fit(x_train,y_train.values.ravel())

/home/shriyaroot/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='warn',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='warn', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('dt',
                              DecisionTreeClassifier(class_weight=None,
                                                     criterion='gini',
                                                     max_depth=None,...
                                        

In [34]:
evc.score(x_test,y_test)

0.6428571428571429